FutureCitiesCatapult/SharingCitiesDashboard

Analytics/importers/tfl_bike_points.py
Analytics/models/attributes.py
Analytics/models/sensor.py
Analytics/models/sensor_attribute.py

creates an importer for available tfl bike spots

tfl bikes importer

---

Analytics/add_datasource.py
Analytics/app.py
Analytics/drop_datasource.py
Analytics/importers/air_quality.py
Analytics/importers/base.py
Analytics/importers/greenwich.py
Analytics/importers/milan.py
Analytics/manage.py
Analytics/models/attributes.py
Analytics/models/sensor.py
Analytics/models/sensor_attribute.py
Analytics/models/theme.py
Analytics/resources/request_for_data.py

created api for backend
created milan importer
also created utilities to add and delete datasource from single python command

Backend api

---

Analytics/app.py
Analytics/requirements.txt

added cors

---

Analytics/importers/air_quality.py
Analytics/importers/base.py
Analytics/importers/greenwich.py
Analytics/importers/milan.py
Analytics/importers/scheduler.py
Analytics/importers/tfl_bike_points.py
Analytics/models/attributes.py
Analytics/models/location.py
Analytics/models/sensor.py
Analytics/models/sensor_attribute.py

built scheduler, it makes use of multiprocesses and every importer can have its own sleep time, the parent process will check for new importers/ create the one which have been killed, periodically
if the main process itself is killed, there is currently no way of recovering from that, however if we start the process as a service then OS can restart it when ever it is killed, which inturn starts the child processes.
Would require careful testing over a period of time, have started it on mac pro and will keep it running overnight

created scheduler, fixed bugs

---

Analytics/requirements.txt
Analytics/resources/helper_functions.py
Analytics/resources/holt_winters.py
Analytics/resources/predict.py
Analytics/resources/request_for_data.py

first version of prediction api. Still lots to do such as error handling

prediction api

---

Analytics/importers/base.py

fixed a bug

---

Analytics/add_datasource.py
Analytics/drop_datasource.py
Analytics/importers/README.md
Analytics/importers/air_quality.py
Analytics/importers/attr_unit_desc.py
Analytics/importers/base.py
Analytics/importers/config.yml.example
Analytics/importers/create_importer.py
Analytics/importers/greenwich.py
Analytics/importers/json_reader.py
Analytics/importers/lisbon.py
Analytics/importers/milan.py
Analytics/importers/read_json.py
Analytics/importers/santander_parking.py
Analytics/importers/scheduler.py
Analytics/importers/tfl_bike_points.py
Analytics/models/api.py
Analytics/models/attributes.py
Analytics/models/location.py
Analytics/models/models.py
Analytics/models/operation.py
Analytics/models/request_analytics.py
Analytics/models/request_table_cols.py
Analytics/models/request_tables.py
Analytics/models/sensor.py
Analytics/models/sensor_attribute.py
Analytics/models/theme.py
Analytics/models/unit.py

Code commenting

---

Analytics/requirements.txt
Analytics/resources/helper_functions.py
Analytics/resources/holt_winters.py
Analytics/resources/predict.py
Analytics/resources/request_for_data.py

uses prophet forecasting engine to generate predictions. It will fail on werker as it requires an update on requirements.txt

prophet forecasting

---

Analytics/importers/scheduler.py

removed the url argument from scheduler as the url gets generated every time when the scheduler runs

removed url as argument

---

Analytics/resources/request_for_data.py
Analytics/resources/request_grouped.py

created a wide format by pivoting the dataframe using Attribute_name.
eg: 0.0.0.0:5000/data?limit=1000&attributedata=O3,CO,SO2&grouped=True&harmonising_method=wide
0.0.0.0:5000/data?limit=1000&attributedata=O3,CO,SO2&grouped=True&harmonising_method=long

added long vs wide format

---

Analytics/importers/air_quality.py
Analytics/importers/base.py
Analytics/importers/greenwich.py
Analytics/importers/milan.py
Analytics/importers/tfl_bike_points.py

Milan meteo

---

Analytics/importers/gla_template_importer.py

gla template importer

---

Analytics/resources/login.py
Frontend/src/actions/userActions.js
Frontend/src/components/LoginPage/LoginForm.js

Linked and working. Mike's endpoint would throw an error if the field wasn't received
Token expiry is also changing:
**Remember:**
**Forget:**

FCC-70 Remember Me Toggle

---

Analytics/app.py
Analytics/models/attribute_alias.py
Analytics/models/attributes.py
Analytics/models/users.py
Analytics/resources/attributes/__init__.py
Analytics/resources/attributes/attribute_alias.py
Analytics/resources/attributes/delete_attribute_alias.py
Analytics/resources/attributes/get_attributes.py
Analytics/resources/attributes/test_attribute_alias.py
Analytics/resources/attributes/test_get_attributes.py
Frontend/src/actions/userActions.js
Frontend/src/components/LoginPage/LoginForm.js

Resources:
+Create/ Update/Read Attribute Alias............ attribute_alias.py
+Delete Attribute Alias....................................delete_attribute_alias.py
+Get Attributes...............................................get_attributes.py
Models:
+Attribute Alias.................attribute_alias.py
Unit tests:
+ Test CRUD Attribute Alias ........................test_attribute_alias.py
+ Test Get Attributes....................................test_get_attributes.py

Add Attribute Alias

---

Analytics/app.py
Analytics/models/theme.py
Analytics/resources/attributes/__init__.py
Analytics/resources/attributes/attribute_alias.py
Analytics/resources/attributes/update_attribute_sub_theme.py
Analytics/resources/themes/add_subtheme.py
Analytics/resources/themes/add_theme.py
Analytics/resources/themes/delete_subtheme.py
Analytics/resources/themes/get_sub_themes.py
Analytics/resources/themes/get_themes.py
Analytics/resources/themes/rename_subtheme.py
Analytics/resources/themes/rename_theme.py
Analytics/resources/themes/test_subthemes.py
Analytics/resources/units/update_unit.py

+ Return empty list when not Themes or SubThemes found
+ SubThemes name must only be unique to the Theme
+ Improved syntax for readability
+ New Params and Types add to docStrings for new SubTheme requirements
+ Added unit tests for new SubTheme requirements
+ Minor bug fixes

Changes Requested In Demo

---

Analytics/db_setup.py

+ Analytics/db_setup.py
+ Create the required unit database entry for importers to execute
+ Create required Theme database entry for importers to execute
+ Create required SubTheme database entry for importers to execute

dB Script to add required depedencies

---

Analytics/add_startup_admin.py
Analytics/manage.py

**New files**
Analytics/add_startup_admin.py - Helper class which prompts an admin individual for their user credentials and then adds the details to the user table. This script is used when the system is deployed in order to create a superuser that can login to the dashboard when it is first accessed
Analytics/manage.py - The helper class is imported and added as a manager command

Fcc 136 create add superuser script

---

Analytics/models/attributes.py
Analytics/resources/themes/get_theme_tree.py

+ sub_theme_id added to JSON Serialize
+ Add RFC-7807 JSON Error message to ThemeTheme Tree

+ Add Theme Id and SubTheme Id to Attribute Branch

---

Analytics/add_startup_admin.py
Analytics/manage.py

**New files**
Analytics/add_startup_admin.py - Helper class which prompts an admin individual for their user credentials and then adds the details to the user table. This script is used when the system is deployed in order to create a superuser that can login to the dashboard when it is first accessed
Analytics/manage.py - The helper class is imported and added as a manager command

Startup superuser setup

---

Analytics/app.py
Analytics/importers/scheduler_new.py

Imported two tables into app.py in order for them to be created when the server starts
moved the location of sys.path.append

Fcc 110 retry importer on failure

---

Analytics/resources/export_data/export_data.py

- Repeating data in pandas DataFrames resolved
- Absolute path support added. The user can now specify the temporary working directory
- GEOJSON support extended to support additional properties
- Attribute-Id None values resolved
- Empty prefix column on CSV export removed

Bug Repeating data when DataFrames merged

---

Analytics/resources/request_for_data.py

**Updated files** 
Analytics/resources/request_for_data.py - added a new state REFUSED, which is set when the either there is not enough data to make a reliable time series prediction or when the supplied user id is not present in the Users table

Fcc 114 timestamp for predictions

---

Analytics/db_setup.py
Analytics/setup_db.sh

Added a script to cover the setup of a deployment DB and incorporated James & Keaton's helper functions into the script.

Db Setup Script

---

Analytics/gunicornserver.py
Analytics/manage.py
CONTAINER-README.md

Changed connection settings to the api and Modified the CONTAINER-README.md file

Docker ready 2

---

CONTAINER-README.md

Added Dataabase initialisation pre-requisites.

Edited the README.md 

---

CONTAINER-README.md

Updated the CONTAINER-README.md file with the steps to get the settings.py file working

Updated the readme file with setting.py information

---

CONTAINER-README.md
Frontend/src/api/urls.js

Updated IP address config instructions for urls.js file

Updated urls.js address

---

Analytics/app.py
Analytics/resources/sendgrid_management.py
Analytics/test_sendgrid_management.py

**New Files**
Analytics/resources/sendgrid_management.py - Contains the resource classes that allow an admin user to test whether the Sendgrid API key environment variable is valid and to replace an invalid api key
Analytics/test_sendgrid_management.py - Contains the tests for sendgrid_management.py
Analytics/app.py - exposed the endpoints for the resource classes in sendgrid_management.py

Fcc 166 implement sengrid endpoints

---

Analytics/resources/moving_sensors/create_tracker.py
Analytics/resources/moving_sensors/delete_location_data.py
Analytics/resources/moving_sensors/delete_tracker.py
Analytics/resources/moving_sensors/get_location_data.py
Analytics/resources/moving_sensors/get_tracker.py
Analytics/resources/moving_sensors/remove_location_data.py
Analytics/resources/moving_sensors/update_tracker.py

+ Add User Authentication to Moving Sensor Endpoints
+ Check JWT claims for Admin Privileges for Tracker CRUD operations

Fcc 165 add user auth to moving sensor endpoints

---

Analytics/resources/moving_sensors/add_new_location_data.py

+ User Auth added to '/add_location_data' endpoint

+ User Auth added to add_location_data endpoint

---

Analytics/resources/moving_sensors/export_to_kml.py
Analytics/resources/moving_sensors/get_dummy_data.py

+ User Auth added to export to kml
+ User Auth added get dummy data

+ User Auth added to export to kml

---

Analytics/app.py
Analytics/celeryconfig.py
Analytics/gunicornserver.py
Analytics/importers/air_quality.py
Analytics/importers/greenwich.py
Analytics/importers/lisbon.py
Analytics/importers/milan.py
Analytics/importers/scheduler_new.py
Analytics/importers/tfl_bike_points.py
Analytics/resources/forgot_password.py
Analytics/resources/moving_sensors/create_tracker.py
Analytics/resources/sendgrid_management.py
Analytics/settings/get_config_decorator.py

+ GetConfig imports changed to relative paths for Docker deployment
+ Gunicorn config added
+ Create tracker Reqparser sub_theme_id argument added

Fcc 162 all settings in one config file

---

Analytics/.gitignore
Analytics/settings/get_config_decorator.py

+ Config File  "config.yml" renamed to "config.env.yml" for Frontend Compatibility with WebKit

+ ConfigFile renamed for Frontend Compatibility with WebKit

---

Analytics/resources/export_data/export_data.py

+ Attribute Unit type added to feature ID

+ Attribute Unit type added to feature ID

---

docker-compose.yml

Added 7 second delay to allow database to be built before starting the API

Updated Docker-Compose file to add delay before starting API

---

Analytics/app.py
Analytics/importers/air_quality.py
Analytics/importers/attr_range_decorator.py
Analytics/importers/greenwich.py
Analytics/importers/lisbon.py
Analytics/importers/milan.py
Analytics/importers/tfl_bike_points.py
Analytics/models/attribute_range.py
Analytics/models/attributes.py
Analytics/resources/changePassword.py
Analytics/test_alert_widget_decorator.py

Analytics/app.py - Imported the new  Attribute range DB model 
Analytics/importers/air_quality.py,| greenwich.py | lisbon.py | tfl_bike_points | milan.py | - appended the attribute range decorator to all the importers 
Analytics/models/attributes.py - Added methods to find the min and max values for an attribute and to retrieve the most recently added timestamp from an attribute table
**New files**
Analytics/importers/attr_range_decorator.py - Queries all attribute tables for their maximum and minimum values after an importer is run
Analytics/models/attribute_range.py - DB model class to store the min and max values of each attribute
Analytics/test_alert_widget_decorator.py - tests the functionality of the alert widget decorator

Fcc 180 alert widget decorator

---

Analytics/importers/attr_range_decorator.py
Analytics/models/alert_model.py
Analytics/models/attribute_range.py
Analytics/models/attributes.py
Analytics/templates/alert_email.html

Analytics/models/attribute_range.py - added the sensor id and recorded date fields for both minimum and maximum attribute values 
Analytics/importers/attr_range_decorator.py - store sensor id as well as the timestamp when the minimum and maximum values were recorded. If a new attribute range is created or one is updated, check the alert model table if any alert emails need be sent
Analytics/models/attributes.py - Created separate functions to retreive the min and max value and returned the oldest minimum and maximum values
**New files**
Analytics/templates/alert_email.html - the html for when a alert email is sent

Fcc 181 alert widget send email

---

Analytics/add_startup_admin.py
Analytics/app.py
Analytics/gunicornserver.py
Analytics/importers/attr_range_decorator.py
Analytics/models/alert_model.py
Analytics/resources/Widgets/save_widgets.py
Analytics/resources/alerts/check_alerts.py
Analytics/resources/alerts/create_alert.py
Analytics/resources/alerts/delete_alert.py
Analytics/resources/alerts/get_alerts.py
Analytics/resources/alerts/push_alert.py

Fcc 183 alert endpoints

---

Analytics/app.py
Analytics/models/alert_model.py
Analytics/resources/Widgets/save_widgets.py

+ Additional alert context add to alert response.
+ HTTP response status code when updating a widget changed to 200(OK).
+ Push Alert endpoint changed to '/alert/triggered' for consistency.

Fcc 183 push alert

---

Analytics/importers/attr_range_decorator.py
Analytics/importers/scheduler_new.py
Analytics/models/attributes.py

**Update files**
Analytics/importers/attr_range_decorator.py - Only check for alerts if the update of an attribute range entry was successful
Analytics/importers/scheduler_new.py - Initialise attribute range entries when the scheduler is run and schedule the importers at 5 minute intervals 
Analytics/models/attributes.py - clear database metadata before a class method's logic is executed

Alert widget fixes

---

Analytics/models/widget.py

+ Delete related Alerts when Widget is deleted

Fcc 196 delete alerts with parent widget

---

deployment/CONTAINER-README.md

Edited the CONTAINER-README.md file

Modified CONTAINER-README.md file with getting started steps

---

Analytics/resources/Widgets/save_widgets.py

~ Default widget layout height and width changed

+ Default Layout Changed

---

Frontend/src/actions/dashboardActions.js
Frontend/src/actions/editorActions.js
Frontend/src/components/Dashboard/GridLayout.js

Fix for widgets not loading with the correct layout

---

Frontend/src/components/LoginPage/RegisterForm.js
Frontend/src/components/common/ChangePasswordModal/ChangePasswordForm.js

Fixed missing error message for "passwords don't match"

---

Analytics/resources/request_for_data.py
Frontend/package-lock.json

exception hardening to prevent critical errors not being caught

Bug fix/prediction error hardening
